### ISSUE TITLE
Updated example available for Vaadin 8

### ISSUE THREAD

**Issue by mrts** [mstahv/vaadin-cdi-jaas-jbossas-example#1]
You might be interested in an updated example that uses Vaadin 8, built-in login form and `@RolesAllowed` annotation for securing views:
https://github.com/mrts/vaadin-javaee-jaas-example

Note that very few extra configuration is needed to get going (no `web.xml` required, at least not in WildFly). With the new defaults in Vaadin 8 and with the built-in login form everything looks really smooth and nice both in the code and in the browser.

Thanks for the good work in making Vaadin 8 really awesome - keep going, Vaadin team :)!

**Comment by mstahv** [comment]
Cool, that looks really nice. Should look into updating this sample as well for 2017. I could add a link to your example from README.md at this point.

**Comment by mrts** [comment]
Thanks :)!
